services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bytebite
      POSTGRES_USER: bytebite
      POSTGRES_PASSWORD: bytebite
    ports:
      - "5433:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
      - rabbitmq
      - redis
      - elasticsearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bytebite
      SPRING_DATASOURCE_USERNAME: bytebite
      SPRING_DATASOURCE_PASSWORD: bytebite
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATA_REDIS_HOST: redis
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
