spring.application.name=bytebite
spring.datasource.url=jdbc:postgresql://localhost:5432/bytebite
spring.datasource.username=bytebite
spring.datasource.password=bytebite
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=Ynl0ZWJpdGVzZWNyZXRrZXltYWtldGhpc3Zlcnlsb25nYW5kcmFuZG9tYXRsZWFzdDI1NmJpdHM=
jwt.expiration=86400000