spring.application.name=bytebite
spring.datasource.url=jdbc:postgresql://localhost:5433/bytebite
spring.datasource.username=bytebite
spring.datasource.password=bytebite
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=Ynl0ZWJpdGVzZWNyZXRrZXltYWtldGhpc3Zlcnlsb25nYW5kcmFuZG9tYXRsZWFzdDI1NmJpdHM=
jwt.expiration=86400000
spring.mvc.problemdetails.enabled=false


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=bytebite-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue=notification-queue
rabbitmq.exchange=notification-exchange
rabbitmq.routing-key=notification

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.elasticsearch.uris=http://localhost:9200